import sys
print("Python version:", sys.version)
print("Platform:", sys.platform)
print("Executable:", sys.executable)
print("Byte order:", sys.byteorder)
print("Max size of an integer:", sys.maxsize)
print("Path:", sys.path)
print("Version info:", sys.version_info)
print("API version:", sys.api_version)
print("Flags:", sys.flags)
print("Hex version:", sys.hexversion)
print("Copyright:", sys.copyright)  